---
- name: velez | packages | install core utilities (Ubuntu/Debian)
  tags: packages,velez
  become: "{{ use_become }}"
  package:
    state: present
    name: "{{ core_packages + [package_names.github_cli.Debian] }}"
  when: ansible_facts["os_family"] == "Debian"

- name: velez | packages | install core utilities (Fedora/RHEL)
  tags: packages,velez
  become: "{{ use_become }}"
  package:
    state: present
    name: "{{ core_packages + [package_names.github_cli.RedHat] }}"
  when: ansible_facts["os_family"] == "RedHat"

- name: velez | packages | install core utilities (Arch Linux)
  tags: packages,velez
  become: "{{ use_become }}"
  community.general.pacman:
    state: present
    name: "{{ core_packages + [package_names.github_cli.Archlinux] }}"
  when: ansible_facts["os_family"] == "Archlinux"
