---
- name: velez | packages | install core utilities (Ubuntu/Debian)
  tags: packages,velez
  become: "{{ use_become }}"
  package:
    state: present
    name:
      - git
      - stow
      - htop
      - tmux
      - neovim
      - mc
      - wget
      - zsh
      - luarocks
      - ripgrep
      - fzf
      - gh
  when: ansible_facts["os_family"] == "Debian"

- name: velez | packages | install core utilities (Fedora/RHEL)
  tags: packages,velez
  become: "{{ use_become }}"
  package:
    state: present
    name:
      - git
      - stow
      - htop
      - tmux
      - neovim
      - mc
      - wget
      - zsh
      - luarocks
      - ripgrep
      - fzf
      - gh
  when: ansible_facts["os_family"] == "RedHat"

- name: velez | packages | install core utilities (Arch Linux)
  tags: packages,velez
  become: "{{ use_become }}"
  community.general.pacman:
    state: present
    name:
      - git
      - stow
      - htop
      - tmux
      - neovim
      - mc
      - wget
      - zsh
      - luarocks
      - ripgrep
      - fzf
      - github-cli
  when: ansible_facts["os_family"] == "Archlinux"
