---
galaxy_info:
  author: velez
  description: Primary user setup for the velez workstation account
  company: Personal
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Fedora
      versions:
        - 36
        - 37
        - 38
    - name: EL
      versions:
        - 8
        - 9
  galaxy_tags:
    - users
    - workstation

dependencies: []
