- block:
  # detect system facts
  - import_tasks: facts/wsl_detection.yml

- block:
  # install users
  - import_tasks: users.yml

- block:
  # configure ssh access
  - import_tasks: ssh.yml

- block:
  # install core software
  - import_tasks: software/packages_utilities.yml
  become: true
